# Generated by Django 5.2.3 on 2025-10-01 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0004_collection_sustainabilitymetric_swap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swap',
            name='collection',
        ),
        migrations.DeleteModel(
            name='SustainabilityMetric',
        ),
        migrations.RemoveField(
            model_name='swap',
            name='user',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='Swap',
        ),
    ]
